# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 107ea60b69c7608f4162a977c52b2636b6a868e73b957c8e8bacde649721bb64ba0d4605c0d3c8083054e9b9e18b9295887b6453317524d5090b0768acf3e004

test:
  secret_key_base: 3274757488816d7874c9bb81158a8fbd05559feb4d561d194b2f54d64d88d9a7e5d7f6de7d1bbcd8b15f509aeb7bb26a389b7f9742848fcf89c63e6042fccf52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
